import {test,expect} from '@playwright/test';
const data=()=>({instances:[{id:'one',workspace_write:true,label:'Vivaldi · Personal',workspaces:[{id:3,name:'Work'}],windows:[{id:1,focused:true,tabs:[{id:10,title:'Example Domain',url:'https://example.com/',workspace_id:3,index:0,active:true}]},{id:2,tabs:[{id:11,title:'Internal settings',url:'vivaldi://settings',workspace_id:0,index:0}]}]},{id:'two',label:'Vivaldi · Other',workspaces:[],windows:[{id:3,tabs:[{id:12,title:'Other tab',url:'https://example.org/',workspace_id:0,index:0}]}]}]});
test('Browser groups every instance/window/workspace, opens native URLs and closes exact desktop tab',async({page:p})=>{
 let snapshot=data();const actions=[];
 await p.route('**/api/browser/snapshot',r=>r.fulfill({json:snapshot}));await p.route('**/api/browser/action',r=>{const q=r.request().postDataJSON();actions.push(q);if(q.action==='close')for(const i of snapshot.instances)for(const w of i.windows)if(i.id===q.instance_id)w.tabs=w.tabs.filter(t=>t.id!==q.tab_id);return r.fulfill({json:{ok:true}})});
 await p.addInitScript(()=>{window.webkit={messageHandlers:{browserDevice:{postMessage:async value=>window.openedBrowser=value}}}});
 await p.goto('/native/');await p.getByText('browser',{exact:true}).first().click();const app=p.locator('#remote-browser-app');await expect(app).toContainText('2 browsers · 3 tabs');await expect(app).toContainText('Work');await expect(app).toContainText('Window 2');await p.waitForTimeout(500);await p.screenshot({path:'artifacts/browser/tabs-multiple.png'});
 await p.getByRole('link',{name:'Open Example Domain on phone'}).click();expect(await p.evaluate(()=>window.openedBrowser.url)).toBe('https://example.com/');expect(actions).toEqual([]);
 await p.getByRole('button',{name:'Open Internal settings on phone'}).click();await expect(app).toContainText('only open on the desktop');
 await p.getByRole('button',{name:'Manage Example Domain'}).click();await p.getByRole('button',{name:'Move…'}).click();await p.getByRole('combobox',{name:'Window',exact:true}).selectOption('2');await p.getByRole('combobox',{name:'Workspace',exact:true}).selectOption('0');await p.getByRole('button',{name:'Move',exact:true}).click();expect(actions.at(-1)).toMatchObject({instance_id:'one',tab_id:10,action:'move',window_id:2,workspace_id:0});
 await p.getByRole('button',{name:'Close Example Domain on desktop'}).click();await expect(app).toContainText('2 browsers · 2 tabs');expect(actions.at(-1)).toMatchObject({instance_id:'one',tab_id:10,action:'close'});await expect(p.getByRole('link',{name:'Open Other tab on phone'})).toBeVisible();
 await p.getByRole('searchbox',{name:'Find a tab'}).fill('Other');await expect(app.locator('.browser-tab')).toHaveCount(1);
});
test('Disconnected Browser explains setup and failed close keeps the tab',async({page:p})=>{
 let snapshot={instances:[]};await p.route('**/api/browser/snapshot',r=>r.fulfill({json:snapshot}));await p.route('**/api/browser/action',r=>r.fulfill({status:400,json:{error:'Browser disconnected'}}));await p.goto('/native/');await p.getByText('browser',{exact:true}).first().click();await expect(p.locator('#remote-browser-app')).toContainText('Connect Vivaldi');snapshot=data();await p.getByRole('button',{name:'Refresh tabs'}).click();await p.getByRole('button',{name:'Close Example Domain on desktop'}).click();await expect(p.locator('#remote-browser-app')).toContainText('Browser disconnected');await expect(p.getByRole('link',{name:'Open Example Domain on phone'})).toBeVisible();
});
