"""Copy installed Omarchy palettes and backgrounds into the portable app (never changes the host theme).

Palettes go to public/themes-data.js, which is committed so hosts without Omarchy still get
the stock catalog. Backgrounds are converted to WebP under public/backgrounds/ with a
catalog.js index; that directory is generated on each host and ignored by git.
"""
import hashlib
import json
import re
import sys
import tomllib
from pathlib import Path

root = Path(__file__).resolve().parent.parent
stock = Path('/usr/share/omarchy/themes')
user = Path.home() / '.config/omarchy/themes'
folder = root / 'public/backgrounds'
names = sorted({p.name for base in (stock, user) if base.exists() for p in base.iterdir() if p.is_dir()})
themes = []
sources = {}
for name in names:
    colors = {}
    for base in (stock, user):
        path = base / name / 'colors.toml'
        if path.exists():
            colors.update(tomllib.loads(path.read_text()))
    if not colors:
        continue
    colors = {k: v for k, v in colors.items() if k == 'mode' or (isinstance(v, str) and v.startswith('#'))}
    for key, value in colors.items():
        if key != 'mode' and (not isinstance(value, str) or not re.fullmatch(r'#[0-9a-fA-F]{6}', value)):
            raise ValueError(f'Invalid color: {name}/{key}')
    backgrounds = {}
    for directory in (stock / name / 'backgrounds', user / name / 'backgrounds', Path.home() / '.config/omarchy/backgrounds' / name):
        if directory.exists():
            for path in sorted(directory.iterdir()):
                if path.is_file() and path.suffix.lower() in ('.jpg', '.jpeg', '.png', '.webp'):
                    backgrounds[path.name] = path
    sources[name] = sorted(backgrounds.items())
    themes.append(dict(id=name, name=name.replace('-', ' ').title(), colors=colors))
if themes:
    (root / 'public/themes-data.js').write_text(
        '// Generated by scripts/import-themes.py from installed Omarchy colors.toml files.\n'
        'window.OmarchyThemeCatalog = ' + json.dumps(themes, indent=2) + ';\n'
    )
else:
    print('No Omarchy themes installed; keeping the committed palettes', file=sys.stderr)
if any(sources.values()):
    try:
        from PIL import Image, ImageOps
    except ImportError:
        raise SystemExit('Converting backgrounds needs Pillow: sudo pacman -S python-pillow (or pip install Pillow)')
folder.mkdir(exist_ok=True)
catalog = {}
keep = set()
for name, files in sources.items():
    entries = []
    for filename, path in files:
        digest = hashlib.sha256(path.read_bytes()).hexdigest()[:16]
        full = folder / (digest + '.webp')
        thumb = folder / (digest + '-thumb.webp')
        keep.update((full.name, thumb.name))
        if not (full.exists() and thumb.exists()):
            with Image.open(path) as source:
                image = ImageOps.exif_transpose(source).convert('RGB')
                image.thumbnail((2560, 2560))
                image.save(full, 'WEBP', quality=82)
                image.thumbnail((400, 400))
                image.save(thumb, 'WEBP', quality=70)
        entries.append(dict(id=digest, name=Path(filename).stem.replace('-', ' ').replace('_', ' '), url='/backgrounds/' + full.name, thumbnail='/backgrounds/' + thumb.name))
    if entries:
        catalog[name] = entries
for stale in folder.glob('*.webp'):
    if stale.name not in keep:
        stale.unlink()
(folder / 'catalog.js').write_text(
    '// Generated by scripts/import-themes.py from the installed Omarchy theme backgrounds.\n'
    'window.OmarchyBackgroundCatalog = ' + json.dumps(catalog, indent=2) + ';\n'
)
print(f'Imported {len(themes)} palettes and {sum(len(v) for v in catalog.values())} backgrounds')
