"""Copy installed Omarchy palettes into the portable app (never changes the host theme)."""
import json
import re
from pathlib import Path
import tomllib

root = Path(__file__).resolve().parent.parent
stock = Path('/usr/share/omarchy/themes')
user = Path.home() / '.config/omarchy/themes'
names = sorted({p.name for base in (stock, user) if base.exists() for p in base.iterdir() if p.is_dir()})
themes = []
for name in names:
    colors = {}
    for base in (stock, user):
        path = base / name / 'colors.toml'
        if path.exists():
            colors.update(tomllib.loads(path.read_text()))
    if not colors:
        continue
    colors = {k: v for k, v in colors.items() if k == 'mode' or (isinstance(v, str) and v.startswith('#'))}
    for key, value in colors.items():
        if key != 'mode' and (not isinstance(value, str) or not re.fullmatch(r'#[0-9a-fA-F]{6}', value)):
            raise ValueError(f'Invalid color: {name}/{key}')
    themes.append(dict(id=name, name=name.replace('-', ' ').title(), colors=colors))
(root / 'public/themes-data.js').write_text('// Generated by scripts/import-themes.py from installed Omarchy colors.toml files.\nwindow.OmarchyThemeCatalog = ' + json.dumps(themes, indent=2) + ';\n')
print(f'Imported {len(themes)} palettes')
