"""Copy installed Omarchy palettes into the portable app (never changes the host theme)."""
import json
import re
from pathlib import Path
import tomllib
import hashlib
from PIL import Image, ImageOps

root = Path(__file__).resolve().parent.parent
stock = Path('/usr/share/omarchy/themes')
user = Path.home() / '.config/omarchy/themes'
names = sorted({p.name for base in (stock, user) if base.exists() for p in base.iterdir() if p.is_dir()})
themes = []
for name in names:
    colors = {}
    for base in (stock, user):
        path = base / name / 'colors.toml'
        if path.exists():
            colors.update(tomllib.loads(path.read_text()))
    if not colors:
        continue
    colors = {k: v for k, v in colors.items() if k == 'mode' or (isinstance(v, str) and v.startswith('#'))}
    for key, value in colors.items():
        if key != 'mode' and (not isinstance(value, str) or not re.fullmatch(r'#[0-9a-fA-F]{6}', value)):
            raise ValueError(f'Invalid color: {name}/{key}')
    backgrounds = {}
    for directory in (stock / name / 'backgrounds', user / name / 'backgrounds', Path.home() / '.config/omarchy/backgrounds' / name):
        if directory.exists():
            for path in sorted(directory.iterdir()):
                if path.is_file() and path.suffix.lower() in ('.jpg', '.jpeg', '.png', '.webp'):
                    backgrounds[path.name] = path
    entries = []
    for filename, path in sorted(backgrounds.items()):
        digest = hashlib.sha256(path.read_bytes()).hexdigest()[:16]
        folder = root / 'public/backgrounds'
        folder.mkdir(exist_ok=True)
        with Image.open(path) as source:
            image = ImageOps.exif_transpose(source).convert('RGB')
            image.thumbnail((2560, 2560))
            image.save(folder / (digest + '.webp'), 'WEBP', quality=82)
            image.thumbnail((400, 400))
            image.save(folder / (digest + '-thumb.webp'), 'WEBP', quality=70)
        entries.append(dict(id=digest, name=Path(filename).stem.replace('-', ' ').replace('_', ' '), url='/backgrounds/' + digest + '.webp', thumbnail='/backgrounds/' + digest + '-thumb.webp'))
    themes.append(dict(backgrounds=entries, id=name, name=name.replace('-', ' ').title(), colors=colors))
(root / 'public/themes-data.js').write_text('// Generated by scripts/import-themes.py from installed Omarchy colors.toml files.\nwindow.OmarchyThemeCatalog = ' + json.dumps(themes, indent=2) + ';\n')
print(f'Imported {len(themes)} palettes and {sum(len(t["backgrounds"]) for t in themes)} backgrounds')
